// Type Imports
import type { UsersType } from '@/types/apps/userTypes'

export const db: UsersType[] = [
  {
    id: 1,
    fullName: 'Jason Cupido',
    company: 'I&J',
    role: 'skipper',
    permit: 'permit1',
    username: 'jason3',
    country: 'South Africa',
    contact: '(27) 81-232-9151',
    email: 'jason0@iandj.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 2,
    fullName: 'Pieter Poggenpoel',
    company: 'Premier Fishing SA ',
    role: 'skipper',
    permit: 'permit2',
    username: 'ppoggenpoel',
    country: 'South Africa',
    contact: '(27) 81-607-9137',
    email: 'pieter@premierfishing.co.za',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 3,
    fullName: 'Marjory Taylor',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit3',
    username: 'mtaylor',
    country: 'South Africa',
    contact: '(021) 264-4599',
    email: 'mtaylor@daff.gov.za',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 4,
    fullName: 'Cyrill Rampies',
    company: 'Sea Harvest Group Ltd',
    role: 'factorycontroller',
    permit: 'permit4',
    username: 'crampies',
    country: 'South Africa',
    contact: '(021) 690-6806',
    email: 'cyrill@seaharvest.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 5,
    fullName: 'Maggy Cupido',
    company: 'Fishermans Deli',
    role: 'outlet',
    permit: 'permit5',
    username: 'mcupido',
    country: 'South Africa',
    contact: '(021) 914-1078',
    email: 'maggy@fishermansdeli.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 6,
    fullName: 'Silvano Halstead',
    company: 'Dunkeld Trout Hatchery',
    role: 'skipper',
    permit: 'permit6',
    username: 'shalstead5',
    country: 'South Africa',
    contact: '(021) 973-3093',
    email: 'shalstead5@dunkeldtrout.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 7,
    fullName: 'Betsie Grootboom',
    company: 'Three Streams Smokehouse',
    role: 'outlet',
    permit: 'permit7',
    username: 'bgrootboom',
    country: 'South Africa',
    contact: '(021) 977-8152',
    email: 'betsie@threestreams.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 8,
    fullName: 'Kate Middletoe',
    company: 'West Coast Aquaculture',
    role: 'skipper',
    permit: 'permit8',
    username: 'kmiddletoe',
    country: 'South Africa',
    contact: '(021) 440-0934',
    email: 'kate@wcaquaculture.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 9,
    fullName: 'Frans Spies',
    company: 'Oceaneers',
    role: 'admin',
    permit: 'permit2',
    username: 'fspies',
    country: 'South Africa',
    contact: '(021) 146-5443',
    email: 'frans@oceaneers.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 10,
    fullName: 'Jillian Petersen',
    company: 'Karoo Catch',
    role: 'driver',
    permit: 'permit1',
    username: 'jpetersen',
    country: 'South Africa',
    contact: '(021) 284-6732',
    email: 'jillian@karoocatch.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 11,
    fullName: 'Jonah Wharlton',
    company: 'ICV AFRICA',
    role: 'skipper',
    permit: 'permit3',
    username: 'jwharlton',
    country: 'South Africa',
    contact: '(021) 532-6824',
    email: 'jwharlton@icv.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 12,
    fullName: 'Shawn Lamb',
    company: 'Viking Aquaculture',
    role: 'outlet',
    permit: 'permit4',
    username: 'slamb',
    country: 'South Africa',
    contact: '(021) 464-0600',
    email: 'shawnlamb@vikingaquaculture.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 13,
    fullName: 'John Legend',
    company: 'Premier Fishing SA',
    role: 'skipper',
    permit: 'permit5',
    username: 'jlegend',
    country: 'South Africa',
    contact: '(021) 284-5083',
    email: 'john@premierfishing.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 14,
    fullName: 'Maximilianus Krause',
    company: 'Caught Online',
    role: 'skipper',
    permit: 'permit6',
    username: 'mkrause',
    country: 'South Africa',
    contact: '(021) 135-7392',
    email: 'mkrause@caughtonline.co.za',
    currentPlan: 'basic',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 15,
    fullName: 'Zeke McCleverty',
    company: 'Afri Jigs',
    role: 'factorycontroller',
    permit: 'permit7',
    username: 'zmcclevertye',
    country: 'South Africa',
    contact: '(021) 409-6565',
    email: 'zmcclevertye@afrijigs.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 16,
    fullName: 'Bentley Emblin',
    company: 'ACMS (Pty) Ltd',
    role: 'skipper',
    permit: 'permit8',
    username: 'bemblin',
    country: 'South Africa',
    contact: '(021) 606-1056',
    email: 'bemblin@acms.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 17,
    fullName: 'Brockie Myles',
    company: 'Abagold Limited',
    role: 'skipper',
    permit: 'permit1',
    username: 'bmyles',
    country: 'South Africa',
    contact: '(021) 225-9905',
    email: 'bmyles@abagold.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 18,
    fullName: 'Bertha Biner',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit2',
    username: 'bbiner',
    country: 'South Africa',
    contact: '(021) 916-9287',
    email: 'bbiner@daff.gov.za',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 19,
    fullName: 'Travis Bruntjen',
    company: 'Sea Harvest Group Ltd',
    role: 'admin',
    permit: 'permit3',
    username: 'tbruntjen',
    country: 'South Africa',
    contact: '(021) 586-6057',
    email: 'tbruntjen@seaharvest.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 20,
    fullName: 'Wesley Burland',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit4',
    username: 'wburland',
    country: 'South Africa',
    contact: '(021) 683-1292',
    email: 'wburlandj@daff.gov.za',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'pending',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 21,
    fullName: 'Selina Kyle',
    company: 'Capricorn Marine',
    role: 'admin',
    permit: 'permit5',
    username: 'catwomen',
    country: 'South Africa',
    contact: '(021) 537-0057',
    email: 'selina@capricornmarine.co.za',
    currentPlan: 'basic',
    status: 'active',
    statusapplications: 'pending',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 22,
    fullName: 'Jameson Lyster',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit6',
    username: 'jlyster',
    country: 'South Africa',
    contact: '(021) 624-0222',
    email: 'jlyster@daff.gov.za',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/8.png'
  },
  {
    id: 23,
    fullName: 'Kare Skitterel',
    company: 'Oceaneers',
    role: 'factorycontroller',
    permit: 'permit7',
    username: 'kskitterel',
    country: 'South Africa',
    contact: '(021) 845-4107',
    email: 'kskitterel@oceaneers.co.za',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 24,
    fullName: 'Cleavland Hadley',
    company: 'MyAquaponics',
    role: 'admin',
    permit: 'permit8',
    username: 'chadley',
    country: 'South Africa',
    contact: '(021) 783-7498',
    email: 'chadley@myaquaponics.co.za',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 25,
    fullName: 'Adeline Micco',
    company: 'Caught Online',
    role: 'admin',
    permit: 'permit1',
    username: 'amicco',
    country: 'South Africa',
    contact: '(021) 598-1841',
    email: 'amicco@caughtonline.co.za',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 26,
    fullName: 'Hugh Hasson',
    company: 'Integrated Aquaculture',
    role: 'admin',
    permit: 'permit2',
    username: 'hhasson',
    country: 'South Africa',
    contact: '(021) 516-1324',
    email: 'hugh@integratedaquaculture.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'pending',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 27,
    fullName: 'Germain Jacobs',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit3',
    username: 'gjacobs',
    country: 'South Africa',
    contact: '(021) 467-5393',
    email: 'germain@daff.gov.za',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 28,
    fullName: 'Bree Kilday',
    company: 'Viking Aquaculture',
    role: 'factorycontroller',
    permit: 'permit4',
    username: 'bkilday',
    country: 'South Africa',
    contact: '(021) 476-0854',
    email: 'bkilday@vikingaquaculture.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 29,
    fullName: 'Candice Pinyon',
    company: 'Premier Fishing SA',
    role: 'factorycontroller',
    permit: 'permit5',
    username: 'cpinyon',
    country: 'South Africa',
    contact: '(021) 683-1520',
    email: 'cpinyon@premierfishing.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 30,
    fullName: 'Isabel Mallindine',
    company: 'Fishermans Deli',
    role: 'outlet',
    permit: 'permit6',
    username: 'imallindine',
    country: 'South Africa',
    contact: '(021) 803-1983',
    email: 'imallindine@fishermansdeli.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '',
    avatarColor: 'info'
  },
  {
    id: 31,
    fullName: 'Gwendolyn Meineken',
    company: 'eatbigfish Africa',
    role: 'admin',
    permit: 'permit7',
    username: 'gmeineken',
    country: 'South Africa',
    contact: '(021) 379-7460',
    email: 'gmeineken@eatbigfishafrica.co.za',
    currentPlan: 'basic',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 32,
    fullName: 'Rafaellle Snowball',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit8',
    username: 'rsnowball',
    country: 'South Africa',
    contact: '(021) 829-0911',
    email: 'rsnowball@daff.gov.za',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 33,
    fullName: 'Rochette Emer',
    company: 'Sea Harvest',
    role: 'admin',
    permit: 'permit1',
    username: 'rochelle',
    country: 'South Africa',
    contact: '(021) 889-3339',
    email: 'rochelle@seaharvest.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/8.png'
  },
  {
    id: 34,
    fullName: 'Ophelie Fibbens',
    company: 'Oceana',
    role: 'admin',
    permit: 'permit2',
    username: 'ofibbens',
    country: 'South Africa',
    contact: '(021) 885-7351',
    email: 'ofibbens@oceana.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 35,
    fullName: 'Stephen MacGilfoyle',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit3',
    username: 'smacgilfoyle',
    country: 'South Africa',
    contact: '(021) 589-8520',
    email: 'smacgilfoyle@daff.gov.za',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 36,
    fullName: 'Bradan Rosebotham',
    company: 'Viking Fishing Company',
    role: 'outlet',
    permit: 'permit4',
    username: 'brosebotham',
    country: 'South Africa',
    contact: '(021) 933-2180',
    email: 'bradan@vikingfishing.co.za',
    currentPlan: 'enterprise',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 37,
    fullName: 'Skip Hebblethwaite',
    company: 'I&J',
    role: 'admin',
    permit: 'permit5',
    username: 'skippy',
    country: 'South Africa',
    contact: '(021) 343-1024',
    email: 'skip@iandj.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 38,
    fullName: 'Moritz Piccard',
    company: 'MyAquaponics',
    role: 'factorycontroller',
    permit: 'permit6',
    username: 'mpiccard',
    country: 'South Africa',
    contact: '(021) 277-2986',
    email: 'mpiccard@myaquaponics.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 39,
    fullName: 'Tyne Widmore',
    company: 'Sealife Equipment (Pty) Ltd',
    role: 'outlet',
    permit: 'permit7',
    username: 'twidmore',
    country: 'South Africa',
    contact: '(021) 731-0928',
    email: 'twidmore@sealife.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 40,
    fullName: 'Florenza Desporte',
    company: 'Afri Jigs',
    role: 'skipper',
    permit: 'permit8',
    username: 'fdesporte',
    country: 'South Africa',
    contact: '(021) 104-2638',
    email: 'fdesporte@afrijigs.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'denied',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 41,
    fullName: 'Edwina Baldetti',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit1',
    username: 'ebaldetti',
    country: 'South Africa',
    contact: '(021) 329-3578',
    email: 'ebaldetti@daff.gov.za',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'info'
  },
  {
    id: 42,
    fullName: 'Benedetto Rossiter',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit2',
    username: 'brossiter',
    country: 'South Africa',
    contact: '(021) 175-6741',
    email: 'brossiter@daff.gov.za',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 43,
    fullName: 'Micaela McNirlan',
    company: 'Premier Fishing SA',
    role: 'driver',
    permit: 'permit3',
    username: 'mmcnirlan',
    country: 'South Africa',
    contact: '(021) 952-0916',
    email: 'mmcnirlan@premierfishing.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 44,
    fullName: 'Vladamir Koschek',
    company: 'Cape Nordic Corporation',
    role: 'skipper',
    permit: 'permit4',
    username: 'vkoschek',
    country: 'South Africa',
    contact: '(021) 758-8335',
    email: 'vkoschek@capenordic.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 45,
    fullName: 'Corrie Perot',
    company: 'Karoo Catch',
    role: 'outlet',
    permit: 'permit5',
    username: 'cperot',
    country: 'South Africa',
    contact: '(021) 385-6808',
    email: 'cperot@karoocatch.co.za',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'renewed',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 46,
    fullName: 'Saunder Offner',
    company: 'Three Streams Smokehouse',
    role: 'driver',
    permit: 'permit6',
    username: 'soffner',
    country: 'South Africa',
    contact: '(021) 586-2264',
    email: 'soffner@threestreams.co.za',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 47,
    fullName: 'Karen Courtliff',
    company: 'The South African Fisheries',
    role: 'admin',
    permit: 'permit7',
    username: 'kcourtliff',
    country: 'South Africa',
    contact: '(021) 199-0020',
    email: 'kcourtliff@safisheries.co.za',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 48,
    fullName: 'Onfre Wind',
    company: 'Dunkeld Trout Hatchery',
    role: 'admin',
    permit: 'permit8',
    username: 'owind',
    country: 'South Africa',
    contact: '(021) 262-7270',
    email: 'owind@dunkeldtrout.co.za',
    currentPlan: 'basic',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 49,
    fullName: 'Paulie Durber',
    company: 'Oceaneers',
    role: 'outlet',
    permit: 'permit2',
    username: 'pdurber',
    country: 'South Africa',
    contact: '(021) 676-1275',
    email: 'pdurber@oceaneers.co.za',
    currentPlan: 'outlet',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 50,
    fullName: 'Beverlie Crab',
    company: 'DAFF',
    role: 'monitor',
    permit: 'permit1',
    username: 'bcrab',
    country: 'South Africa',
    contact: '(021) 294-5153',
    email: 'beverlie@daff.gov.za',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  }
]
