// Type Imports
import type { UsersType } from '@/types/apps/userTypes'

export const db: UsersType[] = [
  {
    id: 1,
    fullName: 'Jason Erasmus',
    company: 'I&J',
    role: 'skipper',
    permit: 'Catch IR Nearshore',
    username: 'jason3',
    country: 'South Africa',
    contact: '(27) 81-232-9151',
    email: 'gslixby0@abc.net.au',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 2,
    fullName: 'Halsey Redmore',
    company: 'Premier Fishing SA ',
    role: 'skipper',
    permit: 'Catch Offshore',
    username: 'hredmore1',
    country: 'South Africa',
    contact: '(27) 81-607-9137',
    email: 'hredmore1@imgur.com',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 3,
    fullName: 'Marjory Sicely',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Export Live',
    username: 'msicely2',
    country: 'South Africa',
    contact: '(021) 264-4599',
    email: 'msicely2@who.int',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 4,
    fullName: 'Cyrill Risby',
    company: 'Sea Harvest Group Ltd',
    role: 'factorycontroller',
    permit: 'Catch Offshore',
    username: 'crisby3',
    country: 'South Africa',
    contact: '(021) 690-6806',
    email: 'crisby3@wordpress.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 5,
    fullName: 'Maggy Hurran',
    company: 'Fishermans Deli',
    role: 'outlet',
    permit: 'Catch IR Offshore',
    username: 'mhurran4',
    country: 'South Africa',
    contact: '(021) 914-1078',
    email: 'mhurran4@yahoo.co.jp',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 6,
    fullName: 'Silvain Halstead',
    company: 'Dunkeld Trout Hatchery',
    role: 'skipper',
    permit: 'Catch Nearshore',
    username: 'shalstead5',
    country: 'South Africa',
    contact: '(021) 973-3093',
    email: 'shalstead5@shinystat.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 7,
    fullName: 'Breena Gallemore',
    company: 'Three Streams Smokehouse',
    role: 'outlet',
    permit: 'Transport License',
    username: 'bgallemore6',
    country: 'South Africa',
    contact: '(021) 977-8152',
    email: 'bgallemore6@boston.com',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 8,
    fullName: 'Kathryne Liger',
    company: 'West Coast Aquaculture',
    role: 'skipper',
    permit: 'Export Frozen',
    username: 'kliger7',
    country: 'South Africa',
    contact: '(021) 440-0934',
    email: 'kliger7@vinaora.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 9,
    fullName: 'Franz Scotfurth',
    company: 'Oceaneers',
    role: 'admin',
    permit: 'Catch IR Nearshore',
    username: 'fscotfurth8',
    country: 'South Africa',
    contact: '(021) 146-5443',
    email: 'fscotfurth8@dailymotion.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 10,
    fullName: 'Jillene Bellany',
    company: 'Karoo Catch',
    role: 'driver',
    permit: 'Catch IR Offshore',
    username: 'jbellany9',
    country: 'South Africa',
    contact: '(021) 284-6732',
    email: 'jbellany9@kickstarter.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 11,
    fullName: 'Jonah Wharlton',
    company: 'ICV AFRICA',
    role: 'skipper',
    permit: 'Catch Nearshore',
    username: 'jwharltona',
    country: 'South Africa',
    contact: '(021) 532-6824',
    email: 'jwharltona@oakley.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 12,
    fullName: 'Smeth Halla',
    company: 'Viking Aquaculture',
    role: 'outlet',
    permit: 'Vessel License',
    username: 'shallamb',
    country: 'South Africa',
    contact: '(021) 464-0600',
    email: 'shallamb@hugedomains.com',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 13,
    fullName: 'Yoko Pottie',
    company: 'Premier Fishing SA',
    role: 'skipper',
    permit: 'Vessel License',
    username: 'ypottiec',
    country: 'South Africa',
    contact: '(021) 284-5083',
    email: 'ypottiec@privacy.gov.au',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 14,
    fullName: 'Maximilianus Krause',
    company: 'Caught Online',
    role: 'skipper',
    permit: 'Catch IR Nearshore',
    username: 'mkraused',
    country: 'South Africa',
    contact: '(021) 135-7392',
    email: 'mkraused@stanford.edu',
    currentPlan: 'basic',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 15,
    fullName: 'Zsazsa McCleverty',
    company: 'Afri Jigs',
    role: 'factorycontroller',
    permit: 'Export Live',
    username: 'zmcclevertye',
    country: 'South Africa',
    contact: '(021) 409-6565',
    email: 'zmcclevertye@soundcloud.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 16,
    fullName: 'Bentlee Emblin',
    company: 'ACMS (Pty) Ltd',
    role: 'skipper',
    permit: 'Export Frozen',
    username: 'bemblinf',
    country: 'South Africa',
    contact: '(021) 606-1056',
    email: 'bemblinf@wired.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 17,
    fullName: 'Brockie Myles',
    company: 'Abagold Limited',
    role: 'skipper',
    permit: 'Catch IR Nearshore',
    username: 'bmylesg',
    country: 'South Africa',
    contact: '(021) 225-9905',
    email: 'bmylesg@amazon.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 18,
    fullName: 'Bertha Biner',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Catch IR Offshore',
    username: 'bbinerh',
    country: 'South Africa',
    contact: '(021) 916-9287',
    email: 'bbinerh@mozilla.com',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 19,
    fullName: 'Travus Bruntjen',
    company: 'Sea Harvest Group Ltd',
    role: 'admin',
    permit: 'Catch Nearshore',
    username: 'tbruntjeni',
    country: 'South Africa',
    contact: '(021) 586-6057',
    email: 'tbruntjeni@sitemeter.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 20,
    fullName: 'Wesley Burland',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Catch Offshore',
    username: 'wburlandj',
    country: 'South Africa',
    contact: '(021) 683-1292',
    email: 'wburlandj@uiuc.edu',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'pending',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 21,
    fullName: 'Selina Kyle',
    company: 'Capricorn Marine',
    role: 'admin',
    permit: 'Vessel License',
    username: 'catwomen1940',
    country: 'South Africa',
    contact: '(021) 537-0057',
    email: 'irena.dubrovna@wayne.com',
    currentPlan: 'basic',
    status: 'active',
    statusapplications: 'pending',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 22,
    fullName: 'Jameson Lyster',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Transport License',
    username: 'jlysterl',
    country: 'South Africa',
    contact: '(021) 624-0222',
    email: 'jlysterl@guardian.co.uk',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '/images/avatars/8.png'
  },
  {
    id: 23,
    fullName: 'Kare Skitterel',
    company: 'Oceaneers',
    role: 'factorycontroller',
    permit: 'Export Live',
    username: 'kskitterelm',
    country: 'South Africa',
    contact: '(021) 845-4107',
    email: 'kskitterelm@ainyx.com',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 24,
    fullName: 'Cleavland Hatherleigh',
    company: 'MyAquaponics',
    role: 'admin',
    permit: 'Export Frozen',
    username: 'chatherleighn',
    country: 'South Africa',
    contact: '(021) 783-7498',
    email: 'chatherleighn@washington.edu',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '/images/avatars/2.png'
  },
  {
    id: 25,
    fullName: 'Adeline Micco',
    company: 'Caught Online',
    role: 'admin',
    permit: 'Catch IR Nearshore',
    username: 'amiccoo',
    country: 'South Africa',
    contact: '(021) 598-1841',
    email: 'amiccoo@whitehouse.gov',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'pending',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 26,
    fullName: 'Hugh Hasson',
    company: 'Integrated Aquaculture',
    role: 'admin',
    permit: 'Catch Nearshore',
    username: 'hhassonp',
    country: 'South Africa',
    contact: '(021) 516-1324',
    email: 'hhassonp@bizjournals.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'pending',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 27,
    fullName: 'Germain Jacombs',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Export Live',
    username: 'gjacombsq',
    country: 'South Africa',
    contact: '(021) 467-5393',
    email: 'gjacombsq@jigsy.com',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 28,
    fullName: 'Bree Kilday',
    company: 'Viking Aquaculture',
    role: 'factorycontroller',
    permit: 'Catch IR Offshore',
    username: 'bkildayr',
    country: 'South Africa',
    contact: '(021) 476-0854',
    email: 'bkildayr@mashable.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 29,
    fullName: 'Candice Pinyon',
    company: 'Premier Fishing SA',
    role: 'factorycontroller',
    permit: 'Catch IR Nearshore',
    username: 'cpinyons',
    country: 'South Africa',
    contact: '(021) 683-1520',
    email: 'cpinyons@behance.net',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/7.png'
  },
  {
    id: 30,
    fullName: 'Isabel Mallindine',
    company: 'Fishermans Deli',
    role: 'outlet',
    permit: 'Export Frozen',
    username: 'imallindinet',
    country: 'South Africa',
    contact: '(021) 803-1983',
    email: 'imallindinet@shinystat.com',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '',
    avatarColor: 'info'
  },
  {
    id: 31,
    fullName: 'Gwendolyn Meineken',
    company: 'eatbigfish Africa',
    role: 'admin',
    permit: 'Catch Nearshore',
    username: 'gmeinekenu',
    country: 'South Africa',
    contact: '(021) 379-7460',
    email: 'gmeinekenu@hc360.com',
    currentPlan: 'basic',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 32,
    fullName: 'Rafaellle Snowball',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Catch Offshore',
    username: 'rsnowballv',
    country: 'South Africa',
    contact: '(021) 829-0911',
    email: 'rsnowballv@indiegogo.com',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'approved',
    avatar: '/images/avatars/5.png'
  },
  {
    id: 33,
    fullName: 'Rochette Emer',
    company: 'Sea Harvest',
    role: 'admin',
    permit: 'Vessel License',
    username: 'remerw',
    country: 'South Africa',
    contact: '(021) 889-3339',
    email: 'remerw@blogtalkradio.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/8.png'
  },
  {
    id: 34,
    fullName: 'Ophelie Fibbens',
    company: 'Oceana',
    role: 'admin',
    permit: 'Catch IR Offshore',
    username: 'ofibbensx',
    country: 'South Africa',
    contact: '(021) 885-7351',
    email: 'ofibbensx@booking.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'approved',
    avatar: '/images/avatars/4.png'
  },
  {
    id: 35,
    fullName: 'Stephen MacGilfoyle',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Export Frozen',
    username: 'smacgilfoyley',
    country: 'South Africa',
    contact: '(021) 589-8520',
    email: 'smacgilfoyley@bigcartel.com',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 36,
    fullName: 'Bradan Rosebotham',
    company: 'Viking Fishing Company',
    role: 'outlet',
    permit: 'Catch IR Offshore',
    username: 'brosebothamz',
    country: 'South Africa',
    contact: '(021) 933-2180',
    email: 'brosebothamz@tripadvisor.com',
    currentPlan: 'enterprise',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 37,
    fullName: 'Skip Hebblethwaite',
    company: 'I&J',
    role: 'admin',
    permit: 'Vessel License',
    username: 'shebblethwaite10',
    country: 'South Africa',
    contact: '(021) 343-1024',
    email: 'shebblethwaite10@iandj.co.za',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 38,
    fullName: 'Moritz Piccard',
    company: 'MyAquaponics',
    role: 'factorycontroller',
    permit: 'Catch Offshore',
    username: 'mpiccard11',
    country: 'South Africa',
    contact: '(021) 277-2986',
    email: 'mpiccard11@vimeo.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'denied',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 39,
    fullName: 'Tyne Widmore',
    company: 'Sealife Equipment (Pty) Ltd',
    role: 'outlet',
    permit: 'Transport License',
    username: 'twidmore12',
    country: 'South Africa',
    contact: '(021) 731-0928',
    email: 'twidmore12@bravesites.com',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 40,
    fullName: 'Florenza Desporte',
    company: 'Afri Jigs',
    role: 'skipper',
    permit: 'Catch Offshore',
    username: 'fdesporte13',
    country: 'South Africa',
    contact: '(021) 104-2638',
    email: 'fdesporte13@omniture.com',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'denied',
    avatar: '/images/avatars/6.png'
  },
  {
    id: 41,
    fullName: 'Edwina Baldetti',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Catch IR Nearshore',
    username: 'ebaldetti14',
    country: 'South Africa',
    contact: '(021) 329-3578',
    email: 'ebaldetti14@theguardian.com',
    currentPlan: 'team',
    status: 'pending',
    statusapplications: 'denied',
    avatar: '',
    avatarColor: 'info'
  },
  {
    id: 42,
    fullName: 'Benedetto Rossiter',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Catch IR Offshore',
    username: 'brossiter15',
    country: 'South Africa',
    contact: '(021) 175-6741',
    email: 'brossiter15@craigslist.org',
    currentPlan: 'team',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 43,
    fullName: 'Micaela McNirlan',
    company: 'Premier Fishing SA',
    role: 'driver',
    permit: 'Export Live',
    username: 'mmcnirlan16',
    country: 'South Africa',
    contact: '(021) 952-0916',
    email: 'mmcnirlan16@hc360.com',
    currentPlan: 'company',
    status: 'inactive',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 44,
    fullName: 'Vladamir Koschek',
    company: 'Cape Nordic Corporation',
    role: 'skipper',
    permit: 'Catch Offshore',
    username: 'vkoschek17',
    country: 'Guatemala',
    contact: '(021) 758-8335',
    email: 'vkoschek17@abc.net.au',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'success'
  },
  {
    id: 45,
    fullName: 'Corrie Perot',
    company: 'Karoo Catch',
    role: 'outlet',
    permit: 'Catch Nearshore',
    username: 'cperot18',
    country: 'South Africa',
    contact: '(021) 385-6808',
    email: 'cperot18@goo.ne.jp',
    currentPlan: 'enterprise',
    status: 'pending',
    statusapplications: 'renewed',
    avatar: '/images/avatars/3.png'
  },
  {
    id: 46,
    fullName: 'Saunder Offner',
    company: 'Three Streams Smokehouse',
    role: 'driver',
    permit: 'Catch Nearshore',
    username: 'soffner19',
    country: 'South Africa',
    contact: '(021) 586-2264',
    email: 'soffner19@mac.com',
    currentPlan: 'company',
    status: 'pending',
    statusapplications: 'renewed',
    avatar: '',
    avatarColor: 'primary'
  },
  {
    id: 47,
    fullName: 'Karena Courtliff',
    company: 'The South African Fisheries',
    role: 'admin',
    permit: 'Catch IR Nearshore',
    username: 'kcourtliff1a',
    country: 'South Africa',
    contact: '(021) 199-0020',
    email: 'kcourtliff1a@bbc.co.uk',
    currentPlan: 'company',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/1.png'
  },
  {
    id: 48,
    fullName: 'Onfre Wind',
    company: 'Dunkeld Trout Hatchery',
    role: 'admin',
    permit: 'Transport License',
    username: 'owind1b',
    country: 'South Africa',
    contact: '(021) 262-7270',
    email: 'owind1b@yandex.ru',
    currentPlan: 'basic',
    status: 'pending',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'error'
  },
  {
    id: 49,
    fullName: 'Paulie Durber',
    company: 'Oceaneers',
    role: 'outlet',
    permit: 'Catch IR Offshore',
    username: 'pdurber1c',
    country: 'South Africa',
    contact: '(021) 676-1275',
    email: 'pdurber1c@gov.uk',
    currentPlan: 'outlet',
    status: 'inactive',
    statusapplications: 'new',
    avatar: '',
    avatarColor: 'warning'
  },
  {
    id: 50,
    fullName: 'Beverlie Krabbe',
    company: 'DAFF',
    role: 'monitor',
    permit: 'Vessel License',
    username: 'bkrabbe1d',
    country: 'South Africa',
    contact: '(021) 294-5153',
    email: 'bkrabbe1d@home.pl',
    currentPlan: 'team',
    status: 'active',
    statusapplications: 'new',
    avatar: '/images/avatars/2.png'
  }
]
